### ISSUE TITLE
node-manta nodejs version support

### ISSUE THREAD

**Issue by IanWyszynski** [joyent/node-manta#318]
At a recent manta call, we found that it would be useful to have documentation on which versions of the node-manta client are supported so that users don't install an arbitrary version and find unexpected behavior. I'd like to have the test suite for at least the LTS v4, v6, and v8 of the client pass or at least document which do and which don't. 

Posting this here for comments, thoughts about which versions take highest priority for something like this. Links/pointers to downloads for the various binaries would also be appreciated.

**Comment by davepacheco** [comment]
In general, I think we want to cover the latest release within whichever major versions we're using for any Manta-using components, plus the latest in each active Node LTS release and the latest non-LTS release.  Right now, I think that means: 0.10, 0.12, and v4 (because we're running them), plus v6 (because it's the current LTS), plus v8 (because it's the current non-LTS, and will be LTS later this year).  Obviously, we should move components off of 0.10, 0.12, and v4 as soon as reasonable, but in practice, I think it's going to be a little while before we're off of these old releases.

I'm hoping this testing won't be too bad because we tested v0.10 up through the current Node v6 at the time when we released v3.0.0.

You can find downloads for old releases here: https://nodejs.org/en/download/releases/

Thanks for picking this up!

**Comment by trentm** [comment]
Note all `make testall` in the node-manta Makefile that is meant to help with this.

**Comment by IanWyszynski** [comment]
I've run the test-suite for the latest version of node-manta with nodejs versions 0.10.48, 0.12.18, 4.8.4, 6.11.2 and 8.3.0. They pass all but the mpu tests.  Where is the proper place to document these results?

**Comment by davepacheco** [comment]
I think we should document this in the README, maybe under a new "Supported Node Versions" section or something.  @askfongjojo, are there other places where this needs to be mentioned to clarify it for new users?

**Comment by trentm** [comment]
Should we also mention supported platforms?

**Comment by askfongjojo** [comment]
Having it in one place (the apidocs) for Supported Node Versions should be good enough. I'll take a look at other docs that may have a reference to node-manta. If needed, they should just have a link to the apidocs instead of duplicating the information, including the supported versions.

**Comment by davepacheco** [comment]
I think the Node specific version stuff probably belongs in this README rather than the public REST API docs.  This may change over time and it's associated with the node-manta version, not the API.

Maybe we could duplicate it in the API docs if that's useful, or refer people to the docs for the version of node-manta that they're using?

**Comment by IanWyszynski** [comment]
What should we say about the fact that the MPU tests are not passing? Is this functionality not officially supported yet?

**Comment by davepacheco** [comment]
MPU requires server-side support.  I'm guessing that you're testing against a server that doesn't support MPU (e.g., our public us-east deployment).  If you want to be sure, you could run the tests against our staging environment (which has MPU enabled), but I think at this point we have enough to say that the versions you tested are supported.
